[[redirects]]
  from = "/*"
  to = "http://api.qrserver.com/v1/read-qr-code/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
